name: Deploy to Humanitec

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build-image-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build and Push to Humanitec
      uses: humanitec/build-push-to-humanitec@v1
      with:
        humanitec-token: ${{ secrets.HUMANITEC_TOKEN }}
        image-name: react-example
        organization: azizdemo
